version: '3.8'

services:
  app:
    build: .
    ports:
      - '9000:9000'
    environment:
      TZ: Asia/Shanghai
      PORT: 9000
      DBHOST: localhost
      DBPORT: 3306
      DBUSER: root
      DBPASS: password
      DBNAME: coreprotect
    init: true
